# Generated by Django 5.1.2 on 2024-11-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0002_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
