# Generated by Django 4.1 on 2024-12-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0005_libro_genero_libro_lenguaje_libro_publicacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="publicacion",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AlterField(
            model_name="libro",
            name="ventas",
            field=models.IntegerField(default=0),
        ),
    ]
