# Generated by Django 4.1 on 2024-12-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0006_alter_libro_publicacion_alter_libro_ventas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="libro",
            old_name="genero",
            new_name="generoq",
        ),
        migrations.RenameField(
            model_name="libro",
            old_name="lenguaje",
            new_name="lenguajeq",
        ),
        migrations.RenameField(
            model_name="libro",
            old_name="publicacion",
            new_name="publicacionq",
        ),
        migrations.RenameField(
            model_name="libro",
            old_name="ventas",
            new_name="ventasq",
        ),
    ]
