# Generated by Django 4.1 on 2024-12-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0007_rename_genero_libro_generoq_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="libro",
            old_name="generoq",
            new_name="genero",
        ),
        migrations.RenameField(
            model_name="libro",
            old_name="lenguajeq",
            new_name="lenguaje",
        ),
        migrations.RenameField(
            model_name="libro",
            old_name="publicacionq",
            new_name="publicacion",
        ),
        migrations.RenameField(
            model_name="libro",
            old_name="ventasq",
            new_name="ventas",
        ),
    ]
