# Generated by Django 4.1 on 2024-12-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0008_rename_generoq_libro_genero_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="genero",
            field=models.IntegerField(default=0),
        ),
    ]
