# Generated by Django 4.1 on 2024-12-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0009_alter_libro_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="genero",
            field=models.CharField(default="Desconocido", max_length=30),
        ),
        migrations.AlterField(
            model_name="libro",
            name="publicacion",
            field=models.IntegerField(default=0),
        ),
    ]
